export const contactContent = {
  heading: 'Get in Touch',
  intro: 'We work with procurement managers, brand managers, and marketing teams running custom metal gift programmes — from a single product line to full multi-SKU sets.',
  email: 'inquiries@wischosgift.com',
  emailLabel: 'Email',
  linkedin: 'https://linkedin.com/company/wischosgift',
  linkedinLabel: 'LinkedIn',
  instagram: 'https://www.instagram.com/wischosgift',
  instagramLabel: 'Instagram',
  responseTime: 'All inquiries are reviewed and responded to within 2 business days.',
  formHeading: 'Send an Inquiry',
  companyLabel: 'Company',
  companyName: 'Anhui Wischos International Trading Co. Ltd',
  addressLabel: 'Address',
  address: 'Room 1125, Office Building No., Baizhuang Fortune Plaza, Jiujiang District, Wuhu City, Anhui Province, China',
} as const
