/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123LocaleChar125InquiryRouteImport } from './routes/{-$locale}/inquiry'
import { Route as Char123LocaleChar125HowItWorksRouteImport } from './routes/{-$locale}/how-it-works'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125ProductsIndexRouteImport } from './routes/{-$locale}/products/index'
import { Route as Char123LocaleChar125ProductsProductIdRouteImport } from './routes/{-$locale}/products/$productId'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125InquiryRoute =
  Char123LocaleChar125InquiryRouteImport.update({
    id: '/inquiry',
    path: '/inquiry',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125HowItWorksRoute =
  Char123LocaleChar125HowItWorksRouteImport.update({
    id: '/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProductsIndexRoute =
  Char123LocaleChar125ProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProductsProductIdRoute =
  Char123LocaleChar125ProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/inquiry': typeof Char123LocaleChar125InquiryRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/inquiry': typeof Char123LocaleChar125InquiryRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/how-it-works': typeof Char123LocaleChar125HowItWorksRoute
  '/{-$locale}/inquiry': typeof Char123LocaleChar125InquiryRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/inquiry'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/inquiry'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/products'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/how-it-works'
    | '/{-$locale}/inquiry'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/inquiry': {
      id: '/{-$locale}/inquiry'
      path: '/inquiry'
      fullPath: '/{-$locale}/inquiry'
      preLoaderRoute: typeof Char123LocaleChar125InquiryRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/how-it-works': {
      id: '/{-$locale}/how-it-works'
      path: '/how-it-works'
      fullPath: '/{-$locale}/how-it-works'
      preLoaderRoute: typeof Char123LocaleChar125HowItWorksRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/products/': {
      id: '/{-$locale}/products/'
      path: '/products'
      fullPath: '/{-$locale}/products/'
      preLoaderRoute: typeof Char123LocaleChar125ProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/products/$productId': {
      id: '/{-$locale}/products/$productId'
      path: '/products/$productId'
      fullPath: '/{-$locale}/products/$productId'
      preLoaderRoute: typeof Char123LocaleChar125ProductsProductIdRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125HowItWorksRoute: typeof Char123LocaleChar125HowItWorksRoute
  Char123LocaleChar125InquiryRoute: typeof Char123LocaleChar125InquiryRoute
  Char123LocaleChar125ProductsProductIdRoute: typeof Char123LocaleChar125ProductsProductIdRoute
  Char123LocaleChar125ProductsIndexRoute: typeof Char123LocaleChar125ProductsIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125HowItWorksRoute: Char123LocaleChar125HowItWorksRoute,
  Char123LocaleChar125InquiryRoute: Char123LocaleChar125InquiryRoute,
  Char123LocaleChar125ProductsProductIdRoute:
    Char123LocaleChar125ProductsProductIdRoute,
  Char123LocaleChar125ProductsIndexRoute:
    Char123LocaleChar125ProductsIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
