/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123LocaleChar125GiftSetsRouteImport } from './routes/{-$locale}/gift-sets'
import { Route as Char123LocaleChar125FaqRouteImport } from './routes/{-$locale}/faq'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125BlogRouteImport } from './routes/{-$locale}/blog'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as LandingOnboardingGiftSetRouteImport } from './routes/landing/onboarding-gift-set'
import { Route as LandingExecutiveGiftSetRouteImport } from './routes/landing/executive-gift-set'
import { Route as Char123LocaleChar125ProductsIndexRouteImport } from './routes/{-$locale}/products/index'
import { Route as Char123LocaleChar125GiftSetsIndexRouteImport } from './routes/{-$locale}/gift-sets/index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog/index'
import { Route as Char123LocaleChar125ProductsProductIdRouteImport } from './routes/{-$locale}/products/$productId'
import { Route as Char123LocaleChar125GiftSetsSetIdRouteImport } from './routes/{-$locale}/gift-sets/$setId'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}/blog/$slug'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125GiftSetsRoute =
  Char123LocaleChar125GiftSetsRouteImport.update({
    id: '/gift-sets',
    path: '/gift-sets',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125FaqRoute = Char123LocaleChar125FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogRoute =
  Char123LocaleChar125BlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const LandingOnboardingGiftSetRoute =
  LandingOnboardingGiftSetRouteImport.update({
    id: '/landing/onboarding-gift-set',
    path: '/landing/onboarding-gift-set',
    getParentRoute: () => rootRouteImport,
  } as any)
const LandingExecutiveGiftSetRoute = LandingExecutiveGiftSetRouteImport.update({
  id: '/landing/executive-gift-set',
  path: '/landing/executive-gift-set',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125ProductsIndexRoute =
  Char123LocaleChar125ProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125GiftSetsIndexRoute =
  Char123LocaleChar125GiftSetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125GiftSetsRoute,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125BlogRoute,
  } as any)
const Char123LocaleChar125ProductsProductIdRoute =
  Char123LocaleChar125ProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125GiftSetsSetIdRoute =
  Char123LocaleChar125GiftSetsSetIdRouteImport.update({
    id: '/$setId',
    path: '/$setId',
    getParentRoute: () => Char123LocaleChar125GiftSetsRoute,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LocaleChar125BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/landing/executive-gift-set': typeof LandingExecutiveGiftSetRoute
  '/landing/onboarding-gift-set': typeof LandingOnboardingGiftSetRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteWithChildren
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/gift-sets': typeof Char123LocaleChar125GiftSetsRouteWithChildren
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/gift-sets/$setId': typeof Char123LocaleChar125GiftSetsSetIdRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/gift-sets/': typeof Char123LocaleChar125GiftSetsIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/landing/executive-gift-set': typeof LandingExecutiveGiftSetRoute
  '/landing/onboarding-gift-set': typeof LandingOnboardingGiftSetRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/gift-sets/$setId': typeof Char123LocaleChar125GiftSetsSetIdRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/gift-sets': typeof Char123LocaleChar125GiftSetsIndexRoute
  '/{-$locale}/products': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/thank-you': typeof ThankYouRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/landing/executive-gift-set': typeof LandingExecutiveGiftSetRoute
  '/landing/onboarding-gift-set': typeof LandingOnboardingGiftSetRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogRouteWithChildren
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/gift-sets': typeof Char123LocaleChar125GiftSetsRouteWithChildren
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/gift-sets/$setId': typeof Char123LocaleChar125GiftSetsSetIdRoute
  '/{-$locale}/products/$productId': typeof Char123LocaleChar125ProductsProductIdRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/gift-sets/': typeof Char123LocaleChar125GiftSetsIndexRoute
  '/{-$locale}/products/': typeof Char123LocaleChar125ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/thank-you'
    | '/{-$locale}'
    | '/landing/executive-gift-set'
    | '/landing/onboarding-gift-set'
    | '/{-$locale}/about'
    | '/{-$locale}/blog'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/gift-sets'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/gift-sets/$setId'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/blog/'
    | '/{-$locale}/gift-sets/'
    | '/{-$locale}/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/thank-you'
    | '/{-$locale}'
    | '/landing/executive-gift-set'
    | '/landing/onboarding-gift-set'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/gift-sets/$setId'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/blog'
    | '/{-$locale}/gift-sets'
    | '/{-$locale}/products'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/thank-you'
    | '/{-$locale}'
    | '/landing/executive-gift-set'
    | '/landing/onboarding-gift-set'
    | '/{-$locale}/about'
    | '/{-$locale}/blog'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/gift-sets'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/gift-sets/$setId'
    | '/{-$locale}/products/$productId'
    | '/{-$locale}/blog/'
    | '/{-$locale}/gift-sets/'
    | '/{-$locale}/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ThankYouRoute: typeof ThankYouRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  LandingExecutiveGiftSetRoute: typeof LandingExecutiveGiftSetRoute
  LandingOnboardingGiftSetRoute: typeof LandingOnboardingGiftSetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/gift-sets': {
      id: '/{-$locale}/gift-sets'
      path: '/gift-sets'
      fullPath: '/{-$locale}/gift-sets'
      preLoaderRoute: typeof Char123LocaleChar125GiftSetsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/faq': {
      id: '/{-$locale}/faq'
      path: '/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof Char123LocaleChar125FaqRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog': {
      id: '/{-$locale}/blog'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/landing/onboarding-gift-set': {
      id: '/landing/onboarding-gift-set'
      path: '/landing/onboarding-gift-set'
      fullPath: '/landing/onboarding-gift-set'
      preLoaderRoute: typeof LandingOnboardingGiftSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/executive-gift-set': {
      id: '/landing/executive-gift-set'
      path: '/landing/executive-gift-set'
      fullPath: '/landing/executive-gift-set'
      preLoaderRoute: typeof LandingExecutiveGiftSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/products/': {
      id: '/{-$locale}/products/'
      path: '/products'
      fullPath: '/{-$locale}/products/'
      preLoaderRoute: typeof Char123LocaleChar125ProductsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/gift-sets/': {
      id: '/{-$locale}/gift-sets/'
      path: '/'
      fullPath: '/{-$locale}/gift-sets/'
      preLoaderRoute: typeof Char123LocaleChar125GiftSetsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125GiftSetsRoute
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125BlogRoute
    }
    '/{-$locale}/products/$productId': {
      id: '/{-$locale}/products/$productId'
      path: '/products/$productId'
      fullPath: '/{-$locale}/products/$productId'
      preLoaderRoute: typeof Char123LocaleChar125ProductsProductIdRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/gift-sets/$setId': {
      id: '/{-$locale}/gift-sets/$setId'
      path: '/$setId'
      fullPath: '/{-$locale}/gift-sets/$setId'
      preLoaderRoute: typeof Char123LocaleChar125GiftSetsSetIdRouteImport
      parentRoute: typeof Char123LocaleChar125GiftSetsRoute
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125BlogRoute
    }
  }
}

interface Char123LocaleChar125BlogRouteChildren {
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
}

const Char123LocaleChar125BlogRouteChildren: Char123LocaleChar125BlogRouteChildren =
  {
    Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
    Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
  }

const Char123LocaleChar125BlogRouteWithChildren =
  Char123LocaleChar125BlogRoute._addFileChildren(
    Char123LocaleChar125BlogRouteChildren,
  )

interface Char123LocaleChar125GiftSetsRouteChildren {
  Char123LocaleChar125GiftSetsSetIdRoute: typeof Char123LocaleChar125GiftSetsSetIdRoute
  Char123LocaleChar125GiftSetsIndexRoute: typeof Char123LocaleChar125GiftSetsIndexRoute
}

const Char123LocaleChar125GiftSetsRouteChildren: Char123LocaleChar125GiftSetsRouteChildren =
  {
    Char123LocaleChar125GiftSetsSetIdRoute:
      Char123LocaleChar125GiftSetsSetIdRoute,
    Char123LocaleChar125GiftSetsIndexRoute:
      Char123LocaleChar125GiftSetsIndexRoute,
  }

const Char123LocaleChar125GiftSetsRouteWithChildren =
  Char123LocaleChar125GiftSetsRoute._addFileChildren(
    Char123LocaleChar125GiftSetsRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125BlogRoute: typeof Char123LocaleChar125BlogRouteWithChildren
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125FaqRoute: typeof Char123LocaleChar125FaqRoute
  Char123LocaleChar125GiftSetsRoute: typeof Char123LocaleChar125GiftSetsRouteWithChildren
  Char123LocaleChar125ProductsProductIdRoute: typeof Char123LocaleChar125ProductsProductIdRoute
  Char123LocaleChar125ProductsIndexRoute: typeof Char123LocaleChar125ProductsIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125BlogRoute: Char123LocaleChar125BlogRouteWithChildren,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125FaqRoute: Char123LocaleChar125FaqRoute,
  Char123LocaleChar125GiftSetsRoute:
    Char123LocaleChar125GiftSetsRouteWithChildren,
  Char123LocaleChar125ProductsProductIdRoute:
    Char123LocaleChar125ProductsProductIdRoute,
  Char123LocaleChar125ProductsIndexRoute:
    Char123LocaleChar125ProductsIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ThankYouRoute: ThankYouRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  LandingExecutiveGiftSetRoute: LandingExecutiveGiftSetRoute,
  LandingOnboardingGiftSetRoute: LandingOnboardingGiftSetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
